//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltKategori
    {
        public int Id { get; set; }
        public int KategoriId { get; set; }
        public string AltKategoriAdi { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
