//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilan
    {
        public int IlanId { get; set; }
        public string IlanBasligi { get; set; }
        public string ShortDescription { get; set; }
        public string FullDescription { get; set; }
        public bool AnasayfadaGoster { get; set; }
        public bool Published { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.Guid IlanSahibi { get; set; }
        public decimal Fiyati { get; set; }
        public string Lat { get; set; }
        public string Lon { get; set; }
        public string IlanResimleri { get; set; }
        public string Video { get; set; }
        public string PostaKodu { get; set; }
        public System.DateTime IlanTarihi { get; set; }
        public int GoruntulenmeSayisi { get; set; }
        public int AltKategoriId { get; set; }
    }
}
