//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilce
    {
        public ilce()
        {
            this.semt = new HashSet<semt>();
        }
    
        public int ilceID { get; set; }
        public int ilID { get; set; }
        public string ad { get; set; }
    
        public virtual il il { get; set; }
        public virtual ICollection<semt> semt { get; set; }
    }
}
