//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mahalle
    {
        public mahalle()
        {
            this.postakodu = new HashSet<postakodu>();
        }
    
        public int mahalleID { get; set; }
        public int semtID { get; set; }
        public string ad { get; set; }
    
        public virtual semt semt { get; set; }
        public virtual ICollection<postakodu> postakodu { get; set; }
    }
}
