//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mot_Marka
    {
        public mot_Marka()
        {
            this.mot_Model = new HashSet<mot_Model>();
        }
    
        public int Id { get; set; }
        public string Marka { get; set; }
    
        public virtual ICollection<mot_Model> mot_Model { get; set; }
    }
}
