//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mot_Guvenlik
    {
        public int Id { get; set; }
        public int mot_MoturId { get; set; }
        public bool ABSCBS { get; set; }
        public bool Airbag { get; set; }
        public bool Alarm { get; set; }
        public bool Sirtlik { get; set; }
        public bool YanKorumaCubuklari { get; set; }
        public bool OnKorumaCubukları { get; set; }
        public bool DusmeTopuzlari { get; set; }
    
        public virtual mot_Motor mot_Motor { get; set; }
    }
}
