//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Core.Objects;

namespace moto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    using System.Linq;
    
    public partial class motobulvarEntities : DbContext
    {
        public motobulvarEntities()
            : base("name=motobulvarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<il> il { get; set; }
        public DbSet<ilce> ilce { get; set; }
        public DbSet<mahalle> mahalle { get; set; }
        public DbSet<semt> semt { get; set; }
        public DbSet<mot_Durumu> mot_Durumu { get; set; }
        public DbSet<mot_Guvenlik> mot_Guvenlik { get; set; }
        public DbSet<mot_Kimden> mot_Kimden { get; set; }
        public DbSet<mot_Marka> mot_Marka { get; set; }
        public DbSet<mot_Model> mot_Model { get; set; }
        public DbSet<mot_MotorGucu> mot_MotorGucu { get; set; }
        public DbSet<mot_MotorHacmi> mot_MotorHacmi { get; set; }
        public DbSet<mot_Renk> mot_Renk { get; set; }
        public DbSet<mot_SilindirSayisi> mot_SilindirSayisi { get; set; }
        public DbSet<mot_Tipi> mot_Tipi { get; set; }
        public DbSet<mot_Vites> mot_Vites { get; set; }
        public DbSet<postakodu> postakodu { get; set; }
        public DbSet<AltKategori> AltKategori { get; set; }
        public DbSet<Kategori> Kategori { get; set; }
        public DbSet<mot_Motor> mot_Motor { get; set; }
        public DbSet<FavorilereAlinanIlanlar> FavorilereAlinanIlanlar { get; set; }
        public DbSet<Ilan> Ilan { get; set; }
    
        public virtual ObjectResult<sp_PKIlBaglantisi_Result> sp_PKIlBaglantisi(string pKId)
        {
            var pKIdParameter = pKId != null ?
                new ObjectParameter("PKId", pKId) :
                new ObjectParameter("PKId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PKIlBaglantisi_Result>("sp_PKIlBaglantisi", pKIdParameter);
        }
    }
}
