//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class postakodu
    {
        public int pkID { get; set; }
        public Nullable<int> mahalleID { get; set; }
        public int kod { get; set; }
    
        public virtual mahalle mahalle { get; set; }
    }
}
