//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class semt
    {
        public semt()
        {
            this.mahalle = new HashSet<mahalle>();
        }
    
        public int semtID { get; set; }
        public Nullable<int> ilceID { get; set; }
        public string ad { get; set; }
    
        public virtual ilce ilce { get; set; }
        public virtual ICollection<mahalle> mahalle { get; set; }
    }
}
